import Head from 'next/head'
import { Flex, Heading, withAuthenticator } from '@aws-amplify/ui-react'
import { API } from 'aws-amplify'
import { useEffect, useState } from 'react'
import { listRecipes } from '../../src/graphql/queries'
import { ListRecipesQuery } from '@/src/API'
import { GraphQLResult } from '@aws-amplify/api-graphql'
import { BillingPortalLink } from '@/components/BillingPortalLink'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import { Recipe } from '@/src/API'

const MyRecipes = ({ user, signOut }: any) => {
	const [fetchedRecipes, setFetchedRecipes] = useState<
		(Recipe | null)[] | undefined
	>([])

	useEffect(() => {
		async function listRecipesForUser() {
			const res = (await API.graphql({
				query: listRecipes,
			})) as GraphQLResult<ListRecipesQuery>

			console.log(res.data?.listRecipes)
			setFetchedRecipes(res.data?.listRecipes)
		}

		listRecipesForUser()
	}, [])

	return (
		<>
			<Head>
				<title>Otterlicious</title>
				<meta name="description" content="Generated by Otterlicious" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Flex direction={'column'} height={'100vh'} width={'100vw'}>
				<Navbar isAuthPage />

				<Flex
					justifyContent={'center'}
					alignItems={'center'}
					direction="column"
					flex={1}
				>
					<Heading level={2} textAlign={'center'}>
						Welcome to my recipes
					</Heading>
					<BillingPortalLink email={user.attributes.email} />
					{fetchedRecipes?.map((fr) => {
						if (fr) {
							return (
								<div key={fr.id} className="card w-96 bg-base-100 shadow-xl">
									<figure>
										<img
											src={`https://d7a5ixq16qoeo.cloudfront.net/${fr.coverImage}`}
											alt={fr.title}
										/>
									</figure>
									<div className="card-body">
										<h2 className="card-title">
											{fr.title}
											<div className="badge badge-secondary">NEW</div>
										</h2>
										<p>{fr.description}</p>
										<div className="card-actions justify-end">
											<div className="badge badge-outline">Demo</div>
										</div>
									</div>
								</div>
							)
						}
					})}
				</Flex>
				<Footer />
			</Flex>
		</>
	)
}

export default withAuthenticator(MyRecipes, { signUpAttributes: ['email'] })
